source "http://rubygems.org"

gem "sinatra", "~> 1.2.3"
gem "shotgun", "~> 0.9"
gem "haml", "~> 3.1.1"
gem "sass", "~> 3.1.1"
gem "compass", "~> 0.11.1"
gem "grid-coordinates", "~> 1.1.4"
gem "dm-postgres-adapter"
gem "data_mapper", "~> 1.2.0"
gem "sinatra-authentication", "0.4.2"
